`channel: ''` disables snap install
canonical/setup-lxd pull request #5
Opened 2023-01-16 05:05 UTC by barrettj12

If this action is invoked with `channel: ''`, it will not attempt to install/refresh LXD from snap - so you can use the pre-installed LXD version.

Also added some more GitHub tests.

2023-01-16 07:33 UTC, barrettj12 commented
On second thought, maybe `channel: ''` (or unset) should be reserved for the default channel (IINM this can be different from latest/stable?), and we should have an explicit `disable-snap-install` input.

2023-01-16 16:04 UTC, taurus-forever approved these changes
I personally prefer the explicit configuration options (e.g. `disable-snap-install`) and not a magic values.
On a long run it always makes easier to deprecate the option, etc.
Deprecating the value is a way harder.

Also, essentially user might expect identical behavior for:
```
    - name: Setup LXD
      uses: canonical/setup-lxd@[version]
      with:
        channel: ''
```
and 
```
    - name: Setup LXD
      uses: canonical/setup-lxd@[version]
```
While they are dramatically different. It can lead to bad surprises for the end-users.
You are the author, the PR will work for me, I will obey. LGTM.

PR#4 is updated, I close it in favor of this PR.

2023-01-16 23:14 UTC, barrettj12 commented
Yeah, I think I agree that an explicit input is better. I'll change my PR to match.

2023-01-18 08:57 UTC, jnsgruk requested changes
One final change here then I think we're good to go:

If `channel` is unset, we still need to check if LXD is installed, and install with `snap install lxd` if it isn't. I don't like the idea that `canonical/setup-lxd` could fail due to not installing LXD ;-)

2023-01-18 16:49 UTC, merged